CREATE TABLE BRAND (
    ID   INTEGER      NOT NULL AUTO_INCREMENT,
    NAME VARCHAR_IGNORECASE(128) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PRICES (
	PRICE_LIST BIGINT NOT NULL AUTO_INCREMENT,
    BRAND_ID INTEGER NOT NULL,
	START_DATE TIMESTAMP NOT NULL,
	END_DATE TIMESTAMP NOT NULL,
	PRODUCT_ID BIGINT NOT NULL,
	PRIORITY INTEGER NOT NULL,
	PRICE NUMERIC(20,2) NOT NULL,
	CURR VARCHAR_IGNORECASE(10) NOT NULL,
    PRIMARY KEY (PRICE_LIST),
    FOREIGN KEY (BRAND_ID) REFERENCES BRAND(ID)
); 